# Generated by Django 6.0.5 on 2026-05-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleicoes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voto",
            options={"verbose_name": "Voto", "verbose_name_plural": "Votos"},
        ),
    ]
