# Generated by Django 6.0.5 on 2026-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleicoes", "0002_alter_voto_options_registrovotacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleitor",
            name="nome",
            field=models.CharField(
                help_text="Nome completo do eleitor",
                max_length=150,
                verbose_name="Nome Completo",
            ),
        ),
        migrations.AlterField(
            model_name="voto",
            name="hash_comprovante",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
