# Generated by Django 6.0.5 on 2026-05-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eleicoes", "0002_candidato_migration"),
        (
            "eleicoes",
            "0003_rename_eleicoes_el_email_3702e4_idx_eleicoes_el_email_fea23b_idx_and_more",
        ),
    ]

    operations = []
