# Generated by Django 6.0.5 on 2026-05-13 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eleicoes", "0004_merge_20260513_1853"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidato",
            options={"ordering": ["numero"]},
        ),
        migrations.RemoveIndex(
            model_name="candidato",
            name="eleicoes_ca_eleicao_146015_idx",
        ),
        migrations.RemoveIndex(
            model_name="candidato",
            name="eleicoes_ca_eleicao_c01332_idx",
        ),
        migrations.RemoveIndex(
            model_name="candidato",
            name="eleicoes_ca_nome_ur_612fff_idx",
        ),
        migrations.RenameIndex(
            model_name="eleitor",
            new_name="eleicoes_el_email_fea23b_idx",
            old_name="eleicoes_el_email_3702e4_idx",
        ),
        migrations.RenameIndex(
            model_name="eleitor",
            new_name="eleicoes_el_cpf_ee365c_idx",
            old_name="eleicoes_el_cpf_f0a9d7_idx",
        ),
        migrations.RenameIndex(
            model_name="eleitor",
            new_name="eleicoes_el_ativo_74ce6c_idx",
            old_name="eleicoes_el_ativo_1b267a_idx",
        ),
        migrations.RenameIndex(
            model_name="eleitor",
            new_name="eleicoes_el_data_ca_174554_idx",
            old_name="eleicoes_el_data_ca_d104be_idx",
        ),
        migrations.RenameIndex(
            model_name="voto",
            new_name="eleicoes_vo_eleicao_673325_idx",
            old_name="eleicoes_vo_eleicao_5a9f5f_idx",
        ),
        migrations.AddField(
            model_name="eleicao",
            name="criada_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrador responsável pela criação da eleição",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eleicoes_criadas",
                to="eleicoes.eleitor",
                verbose_name="Criada por",
            ),
        ),
        migrations.AddField(
            model_name="eleicao",
            name="permite_branco",
            field=models.BooleanField(
                default=True,
                help_text="Define se o voto em branco é permitido nesta eleição",
                verbose_name="Permite Voto em Branco",
            ),
        ),
        migrations.AddField(
            model_name="eleicao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("estudantil", "Estudantil"),
                    ("sindical", "Sindical"),
                    ("associacao", "Associação"),
                    ("condominio", "Condomínio"),
                    ("conselho", "Conselho"),
                    ("outra", "Outra"),
                ],
                default="estudantil",
                help_text="Tipo da eleição (estudantil, sindical, associação, etc.)",
                max_length=20,
                verbose_name="Tipo de Eleição",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eleicao",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="eleicao",
            name="data_fim",
            field=models.DateTimeField(
                help_text="Data e hora de término da votação",
                verbose_name="Data e Hora de Término",
            ),
        ),
        migrations.AlterField(
            model_name="eleicao",
            name="data_inicio",
            field=models.DateTimeField(
                help_text="Data e hora de início da votação",
                verbose_name="Data e Hora de Início",
            ),
        ),
        migrations.AlterField(
            model_name="eleicao",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada da eleição",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="eleicao",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("aberta", "Aberta"),
                    ("encerrada", "Encerrada"),
                    ("apurada", "Apurada"),
                ],
                default="rascunho",
                help_text="Status atual da eleição",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="eleicao",
            name="titulo",
            field=models.CharField(
                help_text="Título da eleição", max_length=200, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="eleicao",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
    ]
